POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@edupoint.pl",
  "password": "admin"
}

###

GET http://localhost:8080/api/flashcards
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2VtYWlsIjoiYWRtaW5AZWR1cG9pbnQucGwiLCJ1c2VybmFtZSI6ImFkbWluIiwiY3JlX3RpbWVzdGFtcCI6MTczMjU1NTY5MC43NzM2MTN9.pe1978AiE41CqmXMrFpJA6ot0hfo_b7bg4Bj7aeeJz8


###

POST http://localhost:8080/api/flashcards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2VtYWlsIjoiYWRtaW5AZWR1cG9pbnQucGwiLCJ1c2VybmFtZSI6ImFkbWluIiwiY3JlX3RpbWVzdGFtcCI6MTczMjU1NTY5MC43NzM2MTN9.pe1978AiE41CqmXMrFpJA6ot0hfo_b7bg4Bj7aeeJz8
Content-Type: application/json

{
  "title": "City capitals",
  "description": "Learn city capitals",
  "flashcards": [
    {
      "text_front": "What is the capital of Poland?",
      "text_back": "Warsaw"
    },
    {
      "text_front": "What is the capital of Germany?",
      "text_back": "Berlin"
    }
  ]
}


###
PUT http://localhost:8080/api/flashcards/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2VtYWlsIjoiYWRtaW5AZWR1cG9pbnQucGwiLCJ1c2VybmFtZSI6ImFkbWluIiwiY3JlX3RpbWVzdGFtcCI6MTczMTUxNDgwNC4yMTYxfQ.wTzxP4zssfSh6HHiuxCOTbFo7Gy-cgNqG9cp90d84no
Content-Type: application/json

{
  "title": "City capitals",
  "description": "Learn city capitals",
  "flashcards": [
    {
      "text_front": "What is the capital of Poland?",
      "text_back": "Warsaw"
    },
    {
      "text_front": "What is the capital of France?",
      "text_back": "Paris"
    }
  ]
}

###

DELETE http://localhost:8080/api/flashcards/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2VtYWlsIjoiYWRtaW5AZWR1cG9pbnQucGwiLCJ1c2VybmFtZSI6ImFkbWluIiwiY3JlX3RpbWVzdGFtcCI6MTczMTUxNDgwNC4yMTYxfQ.wTzxP4zssfSh6HHiuxCOTbFo7Gy-cgNqG9cp90d84no



